# -*- coding: utf-8 -*-
"""FCNN for credit card fraud detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XXEoEBvnoG25OsCFz6i74DnblE0Qavp1
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras import layers,models

df=pd.read_csv('/content/drive/MyDrive/creditcard.csv')

df

df.info()

df.isnull().sum().sum()

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df.duplicated().sum()

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df['Amount']=scaler.fit_transform(df[['Amount']])

df['Class'].value_counts()

X=df.drop('Class', axis=1)
y=df['Class']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.20)

from sklearn.utils.class_weight import compute_class_weight
class_weights = compute_class_weight(class_weight='balanced',classes=np.unique(y_train),y=y_train
)

class_weight = dict(enumerate(class_weights))
print(class_weight)



# Building the model
model=models.Sequential([
    layers.Dense(128,activation='relu',input_shape=(X_train.shape[1],)),
    layers.Dropout(0.3),

    layers.Dense(64,activation='relu'),
    layers.Dropout(0.2),

    layers.Dense(1,activation='sigmoid') # Changed from 10 to 1 for binary classification
])

model.summary()

#Compiling the model
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

from tensorflow.keras.callbacks import EarlyStopping

#Training the model
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

history = model.fit(
    X_train, y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.2,
    class_weight=class_weight,
    callbacks=[early_stop]
)

loss, accuracy = model.evaluate(X_test, y_test)
print(f"The overall accuracy of the model on the test set is: {accuracy:.4f}")

































